# Generated by Django 6.1 on 2026-10-02 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner", models.CharField(db_index=True, max_length=255)),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "full_name",
                    models.CharField(db_index=True, max_length=512, unique=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.URLField(max_length=500)),
                ("stars", models.PositiveIntegerField(default=0)),
                ("forks", models.PositiveIntegerField(default=0)),
                ("watchers", models.PositiveIntegerField(default=0)),
                ("open_issues", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("default_branch", models.CharField(default="main", max_length=100)),
                ("license", models.CharField(blank=True, max_length=255, null=True)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Repository",
                "verbose_name_plural": "Repositories",
                "ordering": ["-stars", "name"],
            },
        ),
        migrations.CreateModel(
            name="CommitActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("commit_count", models.PositiveIntegerField(default=0)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commit_activities",
                        to="dashboard.repository",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commit Activity",
                "verbose_name_plural": "Commit Activities",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PullRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pr_number", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("merged", "Merged"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("merged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pull_requests",
                        to="dashboard.repository",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pull Request",
                "verbose_name_plural": "Pull Requests",
                "ordering": ["-created_at"],
                "unique_together": {("repository", "pr_number")},
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=100)),
                ("bytes", models.BigIntegerField(default=0)),
                ("percentage", models.FloatField(default=0.0)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="dashboard.repository",
                    ),
                ),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "ordering": ["-bytes"],
                "unique_together": {("repository", "language")},
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=500)),
                (
                    "state",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="dashboard.repository",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue",
                "verbose_name_plural": "Issues",
                "ordering": ["-created_at"],
                "unique_together": {("repository", "issue_number")},
            },
        ),
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(db_index=True, max_length=255)),
                ("contributions", models.PositiveIntegerField(default=0)),
                ("avatar_url", models.URLField(blank=True, max_length=500, null=True)),
                ("profile_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributors",
                        to="dashboard.repository",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contributor",
                "verbose_name_plural": "Contributors",
                "ordering": ["-contributions"],
                "unique_together": {("repository", "username")},
            },
        ),
    ]
