# Generated by Django 6.1 on 2026-10-02 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pullrequest",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="title",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.CreateModel(
            name="RepositoryAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analyzed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("stars", models.PositiveIntegerField(default=0)),
                ("forks", models.PositiveIntegerField(default=0)),
                ("open_issues", models.PositiveIntegerField(default=0)),
                ("health_score", models.PositiveIntegerField(default=0)),
                ("health_tier", models.CharField(default="Good", max_length=50)),
                ("activity_score", models.PositiveIntegerField(default=0)),
                ("issue_score", models.PositiveIntegerField(default=0)),
                ("pr_score", models.PositiveIntegerField(default=0)),
                ("contributor_score", models.PositiveIntegerField(default=0)),
                ("maintenance_score", models.PositiveIntegerField(default=0)),
                ("commits_count", models.PositiveIntegerField(default=0)),
                ("contributors_count", models.PositiveIntegerField(default=0)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="dashboard.repository",
                    ),
                ),
            ],
            options={
                "verbose_name": "Repository Analysis",
                "verbose_name_plural": "Repository Analyses",
                "ordering": ["-analyzed_at"],
            },
        ),
    ]
