# Generated by Django 6.1 on 2026-10-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_pullrequest_closed_at_pullrequest_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="has_issues",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="has_pages",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="repository",
            name="has_wiki",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="repository",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="repository",
            name="is_fork",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="repository",
            name="language",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="license_spdx",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="network_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="repository",
            name="pushed_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="size",
            field=models.PositiveIntegerField(
                default=0, help_text="Repository size in KB"
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="subscribers_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="repository",
            name="topics",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="repositoryanalysis",
            name="analysis_window",
            field=models.CharField(default="90d", max_length=20),
        ),
        migrations.AddField(
            model_name="repositoryanalysis",
            name="data_coverage",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="repositoryanalysis",
            name="issue_resolution_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="repositoryanalysis",
            name="pr_merge_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="repositoryanalysis",
            name="prs_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="issue",
            name="created_at",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="issue",
            name="state",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed")],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pullrequest",
            name="created_at",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="pullrequest",
            name="state",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed"), ("merged", "Merged")],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="created_at",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="repository",
            name="fetched_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="repository",
            name="stars",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="repository",
            name="updated_at",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name="commitactivity",
            unique_together={("repository", "date")},
        ),
        migrations.AddIndex(
            model_name="commitactivity",
            index=models.Index(
                fields=["repository", "-date"], name="dashboard_c_reposit_b1249e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contributor",
            index=models.Index(
                fields=["repository", "-contributions"],
                name="dashboard_c_reposit_28000b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["repository", "state"], name="dashboard_i_reposit_9de3d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["repository", "-created_at"],
                name="dashboard_i_reposit_2482aa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="language",
            index=models.Index(
                fields=["repository", "-bytes"], name="dashboard_l_reposit_282102_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pullrequest",
            index=models.Index(
                fields=["repository", "state"], name="dashboard_p_reposit_466c83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pullrequest",
            index=models.Index(
                fields=["repository", "-created_at"],
                name="dashboard_p_reposit_bb9426_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["owner", "name"], name="dashboard_r_owner_e1ff26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["-fetched_at"], name="dashboard_r_fetched_036264_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repositoryanalysis",
            index=models.Index(
                fields=["repository", "-analyzed_at"],
                name="dashboard_r_reposit_78c3db_idx",
            ),
        ),
    ]
