# Generated by Django 6.1 on 2026-10-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_repository_has_issues_repository_has_pages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositoryanalysis",
            name="snapshot_payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Complete isolated analytics payload for this snapshot",
            ),
        ),
    ]
